name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.14'
          - '8.15'
          - '8.16'
          - '8.17'
          - '8.18'
          - 'dev'
        ocaml_version:
          - 'default'
      fail-fast: false # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-quantumlib.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
