name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**'] # for all submitted Pull Requests

jobs:
  coq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.12'
          - '8.13'
          - '8.14'
          - 'dev'
        ocaml_version: ['4.07-flambda']
      fail-fast: false # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          custom_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
            startGroup "Build project"
              make -j2
            endGroup
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .
